language: php

php: 
  - 7.0
  - 7.1
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install

script: vendor/bin/phpunit --verbose

notifications:
  email:
    on_success: [never]